### ISSUE TITLE
itkwidgets doesn't work with Google Colab

### ISSUE THREAD

**Issue by dave3d** [InsightSoftwareConsortium/itkwidgets#282] opened 2020-02-14 15:35 UTC
I was trying out Google Colab and ITK Widgets doesn't seem to work with it.  When I call itkwidgets.view it says runtime disconnected.  As I understand it, Colab is based on Jupyter Labs.

When I try launch itkwidgets.view in a Jupyter Lab session, I get some text output, but the widget doesn't show up.  The text is a description of the return object, I think.  Here's what it prints out:
    Viewer(geometries=[], gradient_opacity=0.22, point_sets=[], rendered_image=<itkImagePython.itkImageUC3; proxy …

**Comment by thewtex** [comment] 2020-02-20 04:21
Duplicate of #99 -- see the pointer to the related issue there.

**Closed by thewtex** 2020-02-20 04:21 UTC
